FROM python:3.8-slim-buster


WORKDIR /app

COPY Pipfile*  ./

RUN sudo apt-get update && sudo apt-get install -y python3-pip && sudo apt-get pipenv

RUN pip install pipenv && pipenv install && pipenv shell

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]