# Generated by Django 5.0.1 on 2024-01-11 11:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='customer-images')),
                ('birth_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='customer-images')),
                ('streams', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='streams should be positive')])),
                ('likes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='streams should be positive')])),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TuneTracker.artists')),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
    ]
