# Generated by Django 5.0.1 on 2024-01-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuneTracker', '0004_rename_name_song_title_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
